#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2020-10-09 13:38:53.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("run_optimisation() works", {

  expect_error(
    kwb.heatsine.opencpu:::run_optimisation()
    # Argument "json_args" fehlt (ohne Standardwert)
  )

})

